#!/usr/bin/env python3
"""Convert saved CS Circles "page source" HTML files into a WordPress WXR 1.2 file.

Each input file contains a link to the original page (title + URL) and a
<pre> block with the HTML-escaped WordPress post content.
"""
import argparse
import html
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

SITE = "https://cscircles.cemc.uwaterloo.ca"
TITLE_RE = re.compile(
    r'<a href="(https?://cscircles\.cemc\.uwaterloo\.ca/[^"]*)">(.*?)</a>', re.S
)
PRE_RE = re.compile(r"<pre[^>]*>(.*?)</pre>", re.S)
# the source view turns "@file:..." references into links; restore the plain text
ATFILE_LINK_RE = re.compile(r'<a href="[^"]*page-atfile-source\.php[^"]*">(.*?)</a>', re.S)


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = TITLE_RE.search(text)
    if not m:
        raise ValueError(f"{path}: no CS Circles link found")
    url, title = m.group(1), html.unescape(m.group(2)).strip()
    m = PRE_RE.search(text)
    if not m:
        raise ValueError(f"{path}: no <pre> block found")
    raw = ATFILE_LINK_RE.sub(r"\1", m.group(1))
    if re.search(r"<\w", raw):
        raise ValueError(f"{path}: unexpected unescaped tag in content")
    content = html.unescape(raw)
    slug = urlparse(url).path.strip("/") or "de"
    if slug == "de":  # lesson 0 is the German front page
        slug = "0-de"
    return {"title": title, "slug": slug, "content": content, "file": path.name}


def lesson_key(page):
    m = re.match(r"(\d+)([A-Za-z]?)", page["slug"])
    return (int(m.group(1)), m.group(2).lower()) if m else (sys.maxsize, page["slug"])


def cdata(s):
    return "<![CDATA[" + s.replace("]]>", "]]]]><![CDATA[>") + "]]>"


def item(page, post_id, order):
    return f"""
  <item>
    <title>{cdata(page["title"])}</title>
    <link>{SITE}/{page["slug"]}/</link>
    <dc:creator>{cdata("admin")}</dc:creator>
    <guid isPermaLink="false">{SITE}/{page["slug"]}/</guid>
    <description></description>
    <content:encoded>{cdata(page["content"])}</content:encoded>
    <excerpt:encoded>{cdata("")}</excerpt:encoded>
    <wp:post_id>{post_id}</wp:post_id>
    <wp:comment_status>{cdata("closed")}</wp:comment_status>
    <wp:ping_status>{cdata("closed")}</wp:ping_status>
    <wp:post_name>{cdata(page["slug"])}</wp:post_name>
    <wp:status>{cdata("publish")}</wp:status>
    <wp:post_parent>0</wp:post_parent>
    <wp:menu_order>{order}</wp:menu_order>
    <wp:post_type>{cdata("page")}</wp:post_type>
    <wp:post_password>{cdata("")}</wp:post_password>
    <wp:is_sticky>0</wp:is_sticky>
    <category domain="language" nicename="de">{cdata("Deutsch")}</category>
  </item>"""


def wxr(pages):
    items = "".join(item(p, 1000 + i, i) for i, p in enumerate(pages))
    return f"""<?xml version="1.0" encoding="UTF-8" ?>
<!-- CS Circles German lessons, (c) CEMC University of Waterloo, CC BY-NC-SA 3.0 -->
<!-- generated by tools/html2wxr.py -->
<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wfw="http://wellformedweb.org/CommentAPI/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <title>CS Circles</title>
  <link>{SITE}</link>
  <description></description>
  <language>de-DE</language>
  <wp:wxr_version>1.2</wp:wxr_version>
  <wp:base_site_url>{SITE}</wp:base_site_url>
  <wp:base_blog_url>{SITE}</wp:base_blog_url>
  <wp:author>
    <wp:author_id>1</wp:author_id>
    <wp:author_login>{cdata("admin")}</wp:author_login>
    <wp:author_email>{cdata("")}</wp:author_email>
    <wp:author_display_name>{cdata("admin")}</wp:author_display_name>
    <wp:author_first_name>{cdata("")}</wp:author_first_name>
    <wp:author_last_name>{cdata("")}</wp:author_last_name>
  </wp:author>
  <wp:term>
    <wp:term_id>1</wp:term_id>
    <wp:term_taxonomy>{cdata("language")}</wp:term_taxonomy>
    <wp:term_slug>{cdata("de")}</wp:term_slug>
    <wp:term_parent>{cdata("")}</wp:term_parent>
    <wp:term_name>{cdata("Deutsch")}</wp:term_name>
  </wp:term>
  <generator>tools/html2wxr.py</generator>{items}
</channel>
</rss>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source_dir", type=Path, help="folder with saved *.html page sources")
    ap.add_argument("-o", "--output", type=Path, required=True, help="WXR file to write")
    args = ap.parse_args()

    pages = sorted((parse(p) for p in args.source_dir.glob("*.html")), key=lesson_key)
    if not pages:
        sys.exit(f"no *.html files in {args.source_dir}")
    args.output.write_text(wxr(pages), encoding="utf-8")
    for p in pages:
        print(f"{p['slug']:8} {p['title']}")
    print(f"{len(pages)} pages -> {args.output}")


if __name__ == "__main__":
    main()
